Add schedule, remove talks
geekcampsg/website pull request #25
Opened 2017-11-01 23:55 UTC by cheeaun

I assume we don't need the "Talk proposals" section anymore, replaced by this "Schedule" section. Please advise if we need it back. This could be merged once the schedule is finalized for production.

This change looks like this:

![nov-02-2017 07-41-42](https://user-images.githubusercontent.com/2296/32303175-f443a172-bfa1-11e7-91cf-e90757902e66.gif)

Notes:

- Spreadsheet is from http://gsx2json.com/api?id=1DsQpdJxF2N0zAR6UM1ornsI5p4dYTU3n6f3vAtQC1BU&sheet=1&columns=false
- All avatars now point to @choonkeat because spreadsheet will need to be updated with speaker avatar images.
- Schedule is fetched via the `gsx2json` service, with a `cache-first` strategy (get from `localStorage` and render first, while an `AJAX` call is done to fetch the latest one), to ensure schedule always load even when offline (or slow network) and the latest schedule will always load later if there are changes.
- The arrows and talk descriptions will appear conditionally based on the `talkdescription` and `speakername` keys.

2017-11-02 02:39 UTC, hongkheng commented on themes/pacgeek/layouts/partials/schedule.html
> +    var data = localStorage.getItem(key);
Could we add checks for `sessionStorage` when users are using private browsing mode in Safari?

2017-11-02 02:43 UTC, vinamelody commented
Wait for @silverframe to finalise the schedule

2017-11-02 02:45 UTC, hongkheng requested changes
let hold the merge first

2017-11-06 14:39 UTC, elfgoh commented
@silverframe has given the greenlight. Any other blockers?

2017-11-06 14:49 UTC, hongkheng commented
ok let me remove the tag

2017-11-06 14:49 UTC, hongkheng approved these changes

2017-11-06 14:54 UTC, merged